# Generated by Django 5.2.17 on 2026-08-28 14:26

import hashlib
import json
import uuid

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def _canonical_sha256(value):
    encoded = json.dumps(value, sort_keys=True, separators=(",", ":"), ensure_ascii=False).encode("utf-8")
    return hashlib.sha256(encoded).hexdigest()


def backfill_research_provenance(apps, schema_editor):
    ExperimentBatch = apps.get_model("scheduler", "ExperimentBatch")
    ExperimentStudy = apps.get_model("scheduler", "ExperimentStudy")
    ScheduleRun = apps.get_model("scheduler", "ScheduleRun")

    for run in ScheduleRun.objects.filter(dispatch_key__isnull=True).iterator():
        run.dispatch_key = uuid.uuid4()
        run.save(update_fields=["dispatch_key"])

    for batch in ExperimentBatch.objects.filter(study__isnull=True).select_related("snapshot").iterator():
        protocol_manifest = {
            "backfilled_from_experiment_batch_id": batch.pk,
            "classification": "exploratory",
        }
        payload = {
            "mode": "EXPLORATORY",
            "protocol_version": "exploratory-v1",
            "source_snapshot_hash": batch.snapshot.snapshot_hash,
            "scale_percentages": [],
            "seeds": batch.seeds,
            "order_seed": batch.order_seed,
            "deadline_seconds": batch.time_limit_seconds,
            "cpu_limit": batch.cpu_limit,
            "memory_limit_mb": batch.memory_limit_mb or 2048,
            "warmups_per_algorithm_scale": 0,
            "protocol_manifest": protocol_manifest,
        }
        study = ExperimentStudy.objects.create(
            name=f"{batch.name} (legacy exploratory)",
            mode="EXPLORATORY",
            protocol_version="exploratory-v1",
            status=batch.status,
            source_snapshot_id=batch.snapshot_id,
            scale_percentages=[],
            seeds=batch.seeds,
            order_seed=batch.order_seed,
            deadline_seconds=batch.time_limit_seconds,
            cpu_limit=batch.cpu_limit,
            memory_limit_mb=batch.memory_limit_mb or 2048,
            warmups_per_algorithm_scale=0,
            protocol_manifest=protocol_manifest,
            manifest_hash=_canonical_sha256(payload),
            protocol_integrity={
                "formal_eligible": False,
                "reason": "Backfilled protocol-v1 experiment; exploratory evidence only.",
            },
            created_by_id=batch.created_by_id,
        )
        batch.study_id = study.pk
        batch.save(update_fields=["study"])


def noop_reverse(apps, schema_editor):
    # Research-provenance rows are intentionally retained on reverse migrations.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_alter_objectiveprofile_profile_hash'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConstraintPolicyVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rule_code', models.CharField(max_length=80)),
                ('version', models.PositiveIntegerField(default=1)),
                ('title', models.CharField(max_length=200)),
                ('definition', models.TextField()),
                ('classification', models.CharField(choices=[('HARD', 'Hard constraint'), ('SOFT', 'Soft objective')], max_length=8)),
                ('owner_office', models.CharField(max_length=200)),
                ('source', models.TextField()),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('is_approved', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('policy_hash', models.CharField(db_index=True, editable=False, max_length=64, validators=[django.core.validators.RegexValidator(message='Enter a lowercase 64-character SHA-256 digest.', regex='^[0-9a-f]{64}$')])),
            ],
            options={
                'ordering': ['rule_code', '-version'],
            },
        ),
        migrations.CreateModel(
            name='ExperimentStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('mode', models.CharField(choices=[('EXPLORATORY', 'Exploratory analysis'), ('FORMAL', 'Formal study')], default='EXPLORATORY', max_length=12)),
                ('protocol_version', models.CharField(default='exploratory-v1', max_length=40)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('READY', 'Validated and ready'), ('QUEUED', 'Queued'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('INVALID', 'Invalid'), ('CANCELLED', 'Cancelled'), ('FAILED', 'Failed')], default='DRAFT', max_length=10)),
                ('scale_percentages', models.JSONField(default=list)),
                ('seeds', models.JSONField(default=list)),
                ('order_seed', models.PositiveIntegerField(default=0)),
                ('deadline_seconds', models.PositiveIntegerField(default=300, validators=[django.core.validators.MinValueValidator(1)])),
                ('cpu_limit', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('memory_limit_mb', models.PositiveIntegerField(default=2048, validators=[django.core.validators.MinValueValidator(1)])),
                ('warmups_per_algorithm_scale', models.PositiveSmallIntegerField(default=0)),
                ('protocol_manifest', models.JSONField(blank=True, default=dict)),
                ('manifest_hash', models.CharField(db_index=True, editable=False, max_length=64, validators=[django.core.validators.RegexValidator(message='Enter a lowercase 64-character SHA-256 digest.', regex='^[0-9a-f]{64}$')])),
                ('protocol_integrity', models.JSONField(blank=True, default=dict)),
                ('invalid_reason', models.TextField(blank=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReservedTimeBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scope', models.CharField(choices=[('INSTITUTION', 'Institution'), ('COLLEGE', 'College'), ('DEPARTMENT', 'Department'), ('PROGRAM', 'Program'), ('SECTION', 'Section')], max_length=12)),
                ('label', models.CharField(max_length=200)),
                ('reason', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['revision', 'scope', 'label'],
            },
        ),
        migrations.CreateModel(
            name='ReservedTimeBlockSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='schedulerun',
            name='uniq_experiment_algorithm_seed',
        ),
        migrations.AddField(
            model_name='experimentbatch',
            name='actual_scale_percentage',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='experimentbatch',
            name='planned_scale_percentage',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='instructoravailabilityprofile',
            name='acknowledge_no_daily_limit',
            field=models.BooleanField(default=False, help_text='Explicit approved acknowledgement that no daily teaching-atom limit applies.'),
        ),
        migrations.AddField(
            model_name='instructoravailabilityprofile',
            name='max_daily_teaching_atoms',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Approved positive maximum teaching atoms per day.', null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='problemsnapshot',
            name='constraint_manifest_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, validators=[django.core.validators.RegexValidator(message='Enter a lowercase 64-character SHA-256 digest.', regex='^[0-9a-f]{64}$')]),
        ),
        migrations.AddField(
            model_name='problemsnapshot',
            name='fixed_student_limit',
            field=models.PositiveSmallIntegerField(default=50, editable=False, help_text='Uniform section and combined-meeting student limit; not room capacity.'),
        ),
        migrations.AddField(
            model_name='problemsnapshot',
            name='instance_characteristics',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='problemsnapshot',
            name='instructor_daily_load_evidence',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='problemsnapshot',
            name='meeting_headcounts',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='problemsnapshot',
            name='reserved_block_evidence',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='problemsnapshot',
            name='rule_manifest',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='problemsnapshot',
            name='section_headcounts',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='schedulerun',
            name='actual_order',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='schedulerun',
            name='claim_token',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='schedulerun',
            name='configuration_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, validators=[django.core.validators.RegexValidator(message='Enter a lowercase 64-character SHA-256 digest.', regex='^[0-9a-f]{64}$')]),
        ),
        migrations.AddField(
            model_name='schedulerun',
            name='container_image',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='schedulerun',
            name='dependency_versions',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='schedulerun',
            name='dispatch_key',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='schedulerun',
            name='exclusion_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='schedulerun',
            name='failure_category',
            field=models.CharField(blank=True, choices=[('ALGORITHM', 'Algorithm observation'), ('INFRASTRUCTURE', 'Infrastructure failure'), ('USER_CANCELLATION', 'User cancellation'), ('UNCLASSIFIED', 'Unclassified failure')], max_length=20),
        ),
        migrations.AddField(
            model_name='schedulerun',
            name='failure_classified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schedulerun',
            name='failure_classified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='classified_schedule_run_failures', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='schedulerun',
            name='heartbeat_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schedulerun',
            name='host_identity',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='schedulerun',
            name='included_in_analysis',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='schedulerun',
            name='lease_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schedulerun',
            name='pair_attempt',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='schedulerun',
            name='peak_rss_mb',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='schedulerun',
            name='planned_order',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='schedulerun',
            name='process_cpu_seconds',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='schedulerun',
            name='process_identity',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='schedulerun',
            name='purpose',
            field=models.CharField(choices=[('ROUTINE', 'Routine scheduling'), ('TUNING', 'Excluded tuning pilot'), ('WARMUP', 'Excluded warm-up'), ('DIAGNOSTIC', 'Excluded diagnostic'), ('MEASURED', 'Measured formal trial')], default='ROUTINE', max_length=10),
        ),
        migrations.AddField(
            model_name='schedulerun',
            name='replacement_for',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='replacement_run', to='scheduler.schedulerun'),
        ),
        migrations.AddField(
            model_name='schedulerun',
            name='source_commit',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='schedulerun',
            name='worker_manifest',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='section',
            name='expected_enrollment',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Expected students in this section. Formal snapshots require a value from 1 to 50; this is not a room-capacity or chair-count field.', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)]),
        ),
        migrations.AddConstraint(
            model_name='instructoravailabilityprofile',
            constraint=models.CheckConstraint(condition=models.Q(('max_daily_teaching_atoms__isnull', True), ('max_daily_teaching_atoms__gte', 1), _connector='OR'), name='instructor_daily_atoms_positive'),
        ),
        migrations.AddConstraint(
            model_name='instructoravailabilityprofile',
            constraint=models.CheckConstraint(condition=models.Q(('max_daily_teaching_atoms__isnull', True), ('acknowledge_no_daily_limit', False), _connector='OR'), name='instructor_daily_limit_not_both'),
        ),
        migrations.AddConstraint(
            model_name='problemsnapshot',
            constraint=models.CheckConstraint(condition=models.Q(('fixed_student_limit', 50)), name='snapshot_fixed_student_limit_50'),
        ),
        migrations.AddConstraint(
            model_name='schedulerun',
            constraint=models.UniqueConstraint(condition=models.Q(('experiment_batch__isnull', False)), fields=('experiment_batch', 'algorithm', 'seed', 'purpose', 'pair_attempt'), name='uniq_experiment_algorithm_seed_attempt'),
        ),
        migrations.AddConstraint(
            model_name='schedulerun',
            constraint=models.CheckConstraint(condition=models.Q(('process_cpu_seconds__isnull', True), ('process_cpu_seconds__gte', 0), _connector='OR'), name='run_cpu_time_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='schedulerun',
            constraint=models.CheckConstraint(condition=models.Q(('peak_rss_mb__isnull', True), ('peak_rss_mb__gte', 0), _connector='OR'), name='run_peak_rss_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='schedulerun',
            constraint=models.CheckConstraint(condition=models.Q(('pair_attempt__gte', 1)), name='run_pair_attempt_positive'),
        ),
        migrations.AddConstraint(
            model_name='section',
            constraint=models.CheckConstraint(condition=models.Q(('expected_enrollment__isnull', True), models.Q(('expected_enrollment__gte', 1), ('expected_enrollment__lte', 50)), _connector='OR'), name='section_expected_enrollment_1_50'),
        ),
        migrations.AddField(
            model_name='constraintpolicyversion',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_constraint_policy_versions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='constraintpolicyversion',
            name='effective_term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='constraint_policy_versions', to='scheduler.academicterm'),
        ),
        migrations.AddField(
            model_name='experimentstudy',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cancelled_experiment_studies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='experimentstudy',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_experiment_studies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='experimentstudy',
            name='source_snapshot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='experiment_studies', to='scheduler.problemsnapshot'),
        ),
        migrations.AddField(
            model_name='experimentbatch',
            name='study',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='scheduler.experimentstudy'),
        ),
        migrations.AddField(
            model_name='reservedtimeblock',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reserved_time_blocks', to='scheduler.college'),
        ),
        migrations.AddField(
            model_name='reservedtimeblock',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reserved_time_blocks', to='scheduler.department'),
        ),
        migrations.AddField(
            model_name='reservedtimeblock',
            name='policy_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reserved_time_blocks', to='scheduler.constraintpolicyversion'),
        ),
        migrations.AddField(
            model_name='reservedtimeblock',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reserved_time_blocks', to='scheduler.program'),
        ),
        migrations.AddField(
            model_name='reservedtimeblock',
            name='revision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserved_time_blocks', to='scheduler.termdatasetrevision'),
        ),
        migrations.AddField(
            model_name='reservedtimeblock',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reserved_time_blocks', to='scheduler.section'),
        ),
        migrations.AddField(
            model_name='reservedtimeblockslot',
            name='block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slot_links', to='scheduler.reservedtimeblock'),
        ),
        migrations.AddField(
            model_name='reservedtimeblockslot',
            name='time_slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserved_block_slot_links', to='scheduler.timeslot'),
        ),
        migrations.AddField(
            model_name='reservedtimeblock',
            name='time_slots',
            field=models.ManyToManyField(related_name='reserved_time_blocks', through='scheduler.ReservedTimeBlockSlot', to='scheduler.timeslot'),
        ),
        migrations.AddIndex(
            model_name='constraintpolicyversion',
            index=models.Index(fields=['effective_term', 'classification', 'is_approved'], name='scheduler_c_effecti_223dcb_idx'),
        ),
        migrations.AddConstraint(
            model_name='constraintpolicyversion',
            constraint=models.UniqueConstraint(fields=('rule_code', 'version', 'effective_term'), name='uniq_constraint_policy_version'),
        ),
        migrations.AddIndex(
            model_name='experimentstudy',
            index=models.Index(fields=['mode', 'status', 'created_at'], name='scheduler_e_mode_69f5ab_idx'),
        ),
        migrations.AddConstraint(
            model_name='experimentstudy',
            constraint=models.CheckConstraint(condition=models.Q(('deadline_seconds__gte', 1)), name='study_deadline_positive'),
        ),
        migrations.AddConstraint(
            model_name='experimentstudy',
            constraint=models.CheckConstraint(condition=models.Q(('cpu_limit__gte', 1)), name='study_cpu_positive'),
        ),
        migrations.AddConstraint(
            model_name='experimentstudy',
            constraint=models.CheckConstraint(condition=models.Q(('memory_limit_mb__gte', 1)), name='study_memory_positive'),
        ),
        migrations.AddConstraint(
            model_name='reservedtimeblockslot',
            constraint=models.UniqueConstraint(fields=('block', 'time_slot'), name='uniq_reserved_block_time_slot'),
        ),
        migrations.AddIndex(
            model_name='reservedtimeblock',
            index=models.Index(fields=['revision', 'scope', 'is_active'], name='scheduler_r_revisio_719b11_idx'),
        ),
        migrations.AddConstraint(
            model_name='reservedtimeblock',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('college__isnull', True), ('department__isnull', True), ('program__isnull', True), ('scope', 'INSTITUTION'), ('section__isnull', True)), models.Q(('college__isnull', False), ('department__isnull', True), ('program__isnull', True), ('scope', 'COLLEGE'), ('section__isnull', True)), models.Q(('college__isnull', True), ('department__isnull', False), ('program__isnull', True), ('scope', 'DEPARTMENT'), ('section__isnull', True)), models.Q(('college__isnull', True), ('department__isnull', True), ('program__isnull', False), ('scope', 'PROGRAM'), ('section__isnull', True)), models.Q(('college__isnull', True), ('department__isnull', True), ('program__isnull', True), ('scope', 'SECTION'), ('section__isnull', False)), _connector='OR'), name='reserved_block_exact_scope_target'),
        ),
        migrations.RunPython(backfill_research_provenance, noop_reverse),
        migrations.AlterField(
            model_name='schedulerun',
            name='dispatch_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
