# Generated by Django 5.2.17 on 2026-08-28 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_experimental_platform_v2'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructoravailabilityprofile',
            name='daily_load_policy_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='instructor_daily_load_profiles', to='scheduler.constraintpolicyversion'),
        ),
    ]
