# Generated by Django 5.2.17 on 2026-08-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduler", "0004_instructor_daily_load_policy"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="schedulerun",
            index=models.Index(
                fields=["status", "lease_expires_at"],
                name="run_stale_lease_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="schedulerun",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("actual_order__isnull", False),
                    ("experiment_batch__isnull", False),
                ),
                fields=("experiment_batch", "actual_order"),
                name="uniq_batch_actual_run_order",
            ),
        ),
    ]
