# Generated by Django 5.2.17 on 2026-09-05 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0006_dataset_origin'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='schedulereview',
            name='uniq_schedule_college_endorsement',
        ),
    ]
